# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  group: 'webapp1'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

parameters:
- name: iispath # name of the parameter; required
  type: string # data type of the parameter; required
  default: "UN_SET"
- name: appname # name of the parameter; required
  type: string # data type of the parameter; required
  default: "UN_SET"
- name: pspwd # name of the parameter; required
  type: string # data type of the parameter; required
  default: "UN_SET"

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="D:\a\1\a\${{ parameters.appname }}.zip" /p:DeployIisAppPath="${{ parameters.iispath }}"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'PublishProfile'
    PublishProfilePath: '$(System.DefaultWorkingDirectory)/**/*Web Deploy.pubxml'
    PublishProfilePassword: '${{ parameters.pspwd }}'
    packageForLinux: 'D:\a\1\a\${{ parameters.appname }}.zip'
